// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh1ANrl-IgSym38ohnQZE2MaFnyYBKVzk',
    appId: '1:880368061643:web:bd684c81c0f8e604209f4e',
    messagingSenderId: '880368061643',
    projectId: 'superfoods-kitchen',
    authDomain: 'superfoods-kitchen.firebaseapp.com',
    storageBucket: 'superfoods-kitchen.firebasestorage.app',
    databaseURL: 'https://superfoods-kitchen-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHsMsir8qTG7vIq4VDr_cJc6AmnqqUOs',
    appId: '1:880368061643:android:b522ba768ab02f93209f4e',
    messagingSenderId: '880368061643',
    projectId: 'superfoods-kitchen',
    storageBucket: 'superfoods-kitchen.firebasestorage.app',
    databaseURL: 'https://superfoods-kitchen-default-rtdb.firebaseio.com',
  );
}