// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyB_u-9l5g1LQhOHMwdyjIBNHKQZwmPf1F8',
  appId: '1:1075043554354:web:d56e36462e308bf070582b',
  messagingSenderId: '1075043554354',
  projectId: 'drip-too-hard-collection',
  authDomain: 'drip-too-hard-collection.firebaseapp.com',
  storageBucket: 'drip-too-hard-collection.firebasestorage.app',
  databaseURL: 'https://drip-too-hard-collection-default-rtdb.firebaseio.com',
);

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAzE6Mv46Iwu9Yjj9sB2Srexe2_DKuGDYg',
  appId: '1:1075043554354:android:b136215de53b92d970582b',
  messagingSenderId: '1075043554354',
  projectId: 'drip-too-hard-collection',
  storageBucket: 'drip-too-hard-collection.firebasestorage.app',
  databaseURL: 'https://drip-too-hard-collection-default-rtdb.firebaseio.com',
);

}